### ISSUE TITLE
Training from e

### ISSUE THREAD

**Issue by maderix** [AnswerDotAI/fsdp_qlora#19]
I understand the article mostly mentions fine-tuning. But theoretically is it possible to train something like a 7b model from scratch on a single 24GB GPU?
The recent GaLore paper targets this: https://huggingface.co/papers/2403.03507

Do you think something like this can be implemented in this library?

**Comment by jph00** [comment]
For now, it's for finetuning.

The issue of to what degree it might be possible to train a model from scratch using QLoRA is still an open question. The relora paper showed that it can work in some situations, but attempts to scale it up were unsuccessful. The recent DoRA paper perhaps might allow a "re-DoRA" approach to work. If so, that could be combined with quantization to do "re-QDoRA"!
