### ISSUE TITLE
Example with AMD ROCm/HIP

### ISSUE THREAD

**Issue by ehartford** [AnswerDotAI/fsdp_qlora#32]
Can you please provide an example that works with AMD ROCm/HIP?

I would be happy to give access to my server!

**Comment by ehartford** [comment]
I already have pytorch, bitsandbytes, and flash attention working on my server

**Comment by ehartford** [comment]
What changes to flash attention and bitsandbytes do I need to push on getting into the ROCm forks?

**Comment by warner-benjamin** [comment]
@ehartford We published a [technical deep dive](https://www.answer.ai/posts/2024-03-14-fsdp-qlora-deep-dive.html) which covers the changes to quantization libraries and training scripts. 

The short version is FSDP only supports float dtypes while bitsandbytes stored quantized weights in uint8. You'll need to update the AMD fork to add support for the new `quant_storage` argument, which allows users to select which dtype the quantized weights are stored in. Along with some modification to the quant metadata and automatic quantization.

All of the necessary changes to the bitsandbytes are in pull request TimDettmers/bitsandbytes/pull/970.

Hopefully this helps.

**Comment by ehartford** [comment]
Very helpful.  Thank you
